CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "file_versions_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "name" varchar(255) NOT NULL, "email" varchar(254) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "file_versions_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "file_versions_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "file_versions_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "file_versions_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "file_versions_fileversion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file_name" varchar(255) NOT NULL, "version_number" integer unsigned NOT NULL CHECK ("version_number" >= 0), "file_path" varchar(100) NOT NULL, "created_at" datetime NOT NULL, "virtual_path" varchar(500) NOT NULL, "mime_type" varchar(100) NOT NULL, "file_size" integer NOT NULL, "checksum" varchar(64) NOT NULL, "notes" text NOT NULL, "previous_version_id" bigint NULL REFERENCES "file_versions_fileversion" ("id") DEFERRABLE INITIALLY DEFERRED, "root_file_id" bigint NULL REFERENCES "file_versions_fileversion" ("id") DEFERRABLE INITIALLY DEFERRED, "uploader_id" bigint NOT NULL REFERENCES "file_versions_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "unique_root_file_per_user_and_path" ON "file_versions_fileversion" ("virtual_path", "uploader_id") WHERE "previous_version_id" IS NULL;
CREATE UNIQUE INDEX "file_versions_user_groups_user_id_group_id_58677093_uniq" ON "file_versions_user_groups" ("user_id", "group_id");
CREATE INDEX "file_versions_user_groups_user_id_5e198f48" ON "file_versions_user_groups" ("user_id");
CREATE INDEX "file_versions_user_groups_group_id_ef77213c" ON "file_versions_user_groups" ("group_id");
CREATE UNIQUE INDEX "file_versions_user_user_permissions_user_id_permission_id_482fbff2_uniq" ON "file_versions_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "file_versions_user_user_permissions_user_id_d6e329d0" ON "file_versions_user_user_permissions" ("user_id");
CREATE INDEX "file_versions_user_user_permissions_permission_id_652de7e0" ON "file_versions_user_user_permissions" ("permission_id");
CREATE INDEX "file_versions_fileversion_previous_version_id_01384b93" ON "file_versions_fileversion" ("previous_version_id");
CREATE INDEX "file_versions_fileversion_root_file_id_d9dd607a" ON "file_versions_fileversion" ("root_file_id");
CREATE INDEX "file_versions_fileversion_uploader_id_65e5a01a" ON "file_versions_fileversion" ("uploader_id");
CREATE TABLE IF NOT EXISTS "account_emailaddress" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "email" varchar(254) NOT NULL, "verified" bool NOT NULL, "primary" bool NOT NULL, "user_id" bigint NOT NULL REFERENCES "file_versions_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "account_emailaddress_user_id_2c513194" ON "account_emailaddress" ("user_id");
CREATE TABLE IF NOT EXISTS "account_emailconfirmation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "sent" datetime NULL, "key" varchar(64) NOT NULL UNIQUE, "email_address_id" integer NOT NULL REFERENCES "account_emailaddress" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "account_emailconfirmation_email_address_id_5b7f8c58" ON "account_emailconfirmation" ("email_address_id");
CREATE INDEX "account_emailaddress_upper" ON "account_emailaddress" ((UPPER("email")));
CREATE UNIQUE INDEX "unique_verified_email" ON "account_emailaddress" ("email") WHERE "verified";
CREATE UNIQUE INDEX "account_emailaddress_user_id_email_987c8728_uniq" ON "account_emailaddress" ("user_id", "email");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "file_versions_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "authtoken_token" ("key" varchar(40) NOT NULL PRIMARY KEY, "created" datetime NOT NULL, "user_id" bigint NOT NULL UNIQUE REFERENCES "file_versions_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
